name: Upload & Load SQL Dump Files
on:
  workflow_dispatch:

jobs:
  load-dump:
    name: Load Dump
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      id: auth
      with:
        credentials_json: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Upload SQL Files
      run: gsutil -m cp migrations/*.sql gs://${{ secrets.GCS_SQL_BUCKET }}

    - name: Load SQL Files
      run: gcloud sql import sql ${{ secrets.DB_INSTANCE_NAME }} gs://${{ secrets.GCS_SQL_BUCKET }}/tables.sql --database=${{ secrets.DB_NAME }}